### ISSUE TITLE
Create data dictionary

### ISSUE THREAD

**Issue by chriszs** [PublicI/us-polling-places#49]

**Comment by chriszs** [comment]
The core set of columns seem to be:
```
state
election_date
jurisdiction
jurisdiction_type
county_name
municipality
ward
precinct
precinct_id
precinct_name
name
address
polling_place_id
polling_place_type
```

In addition, these fields make one-off appearances:

```
ghost_precinct
notes
county_fips
```

Most of these are self-explanatory, but a data dictionary would help us define an expected schema and explain when certain columns are available (e.g. county_name versus jurisdiction).

**Comment by pratheekrebala** [comment]
This is the schema we used for the 2020 data that we shared with a few partners, I'm going to use the following schema (and update older files accordingly) unless there are any objections @jlagetz

- election_date: date of the election
- state
- county_name _(when it is available)_
- jurisdiction _(specifies a jurisdiction associated with the polling place, most of the time it's county)_
- jurisdiction_type _(this is also usually `county` but in some cases could be different, e.g. `municipality`)_
- precinct_id
- precinct_name
- polling_place_id _(this is mostly blank, but is sometimes available in the source data and could help link to turnout information)_
- location_type _(one of: polling_place, dropbox, vote_center)_
- name
- address
- notes _(any processing notes added by us)_
- source
- source_date _(date the data is acquired, this is mostly only relevant for 2020 data where data was acquired prior to the election)_
- source_notes _(aux field for any additional info we have from the SoS)_
