### ISSUE TITLE
election_date not always present

### ISSUE THREAD

**Issue by chriszs** [PublicI/us-polling-places#51]
Missing from:
```
Kentucky
Louisiana
Maine
Maryland
Massachusetts
Montana
Nebraska
New_Jersey
Oklahoma
Rhode_Island
South_Carolina
South_Dakota
Vermont
Virginia
```

**Comment by pratheekrebala** [comment]
I am considering removing this column altogether since there could have been emergency changes that aren't reflected in our dataset...I'm worried about giving a false sense of precision..

**Comment by chriszs** [comment]
Might make sense to do year instead so the whole thing is still importable without having to pull that from the file name.

**Comment by pratheekrebala** [comment]
Keeping the `election_date` column but also adding a `source_date` column which will indicate the data when the data was acquired.

**Comment by pratheekrebala** [comment]
Addressed in the new schema, export function has been updated to ensure test election date is included for each available file and that the election date matches the one specified in `manifest.yaml`.
