### ISSUE TITLE
Vermont Municipalities incorrect for Burlington and South Burlington

### ISSUE THREAD

**Issue by mvarnold** [PublicI/us-polling-places#62]
For all Vermont years it looks like the precinct name was just copied for the municipality name. Thus Burlington and South Burlington are split into their precincts incorrectly.

**Comment by pratheekrebala** [comment]
Thank you for flagging this, @mvarnold. I am looking into this and will circle back.

**Comment by pratheekrebala** [comment]
Fixed in 1a4ef16138db33b4e49230631abaf3cb49320e34
