### ISSUE TITLE
Status as of July 2021

### ISSUE THREAD

**Issue by igorgeyn** [PublicI/us-polling-places#64]
The documentation for the repository indicates that the September 2020 data is an "initial" data release. Additionally, STATUS.md indicates pending-style statuses for several states. 

Is there currently a possibility that more data will be released in the future? If so, is there an estimate of when that might take place?

**Comment by igorgeyn** [comment]
Hi @pratheekrebala -- thanks for picking this up. Just wondering if this something that CPI plans to update in the (near or distant) future. 

Please do let me know if there is better Github etiquette around this sort of thing. Thanks!

**Comment by pratheekrebala** [comment]
Hey @igorgeyn, we've release additional data for 2020 general election and are continuing to update more datasets.

The current issue with the "Pending" states is primarily that we have several hundred county level FOIA responses that we have to process and standardize. We have limited capacity to handle those but are making our way through them and will update this repo with the additional data when we are done with those. In the mean time, if there are specific states that you are looking for please feel free to reach out to me: prebala@publicintegrity.org; I can provide you with what we have (partially processed or unprocessed raw data) or can try to prioritize those based on your project/need.
