### ISSUE TITLE
Arkansas: 2016 polling locations missing

### ISSUE THREAD

**Issue by Dtphelan1** [PublicI/us-polling-places#65]
*Edit: Updated to be more accurate* 
`data/Arkansas/README.md` indicates that Arkansas should have data for 2016, but there is no such file. If you have that data available, it could be uploaded; if that data is not available, I'd be willing to make a fork and a PR that updates your documentation appropriately. 

Thanks to you and your team for all the amazing effort that went into this.

**Comment by pratheekrebala** [comment]
Thank you for flagging this. I am going to update the status file.

We were unable to get this data from the Secretary of State's office in Arkansas (they do not have these records). We worked with a third party to acquire some of the historical data here but unfortunately the data we received for 2016 had null values for nearly all the precincts so we don't currently have any good source of data for 2016.

The only option remaining is to go to each county and request this data, this is roughly 75 counties. I don't think we have the bandwidth to pursue this at the moment but we would really appreciate any assistance that you or your team might be able to provide with this.

**Comment by Dtphelan1** [comment]
That absolutely makes sense! Sorry to hear that the data isn't recorded/available at the Secretary of State level. 

A minimal fix for this would definitely just be an update to the `data/Arkansas/README.md` file. Let me know if your project is accepting PR's from Forks, and I'd be happy to take a stab at the documentation updates 😄

**Comment by pratheekrebala** [comment]
The README.md and manifest.yaml for AK has been updated to accurately reflect the current status:

https://github.com/PublicI/us-polling-places/tree/update-2020/data/arkansas

**Comment by pratheekrebala** [comment]
@Dtphelan1 (Of-course PR's are always welcome!)
