### ISSUE TITLE
STATUS.md Codes Lack Explanation

### ISSUE THREAD

**Issue by Dtphelan1** [PublicI/us-polling-places#66]
In [`STATUS.md`](https://github.com/PublicI/us-polling-places/blob/release/STATUS.md) a number of codes are used, but there's no clear explanation of what those codes mean. In particular: 
- `Excluded` leaves the question of why these years' or states' had their data excluded. Are there explanations that could be made available?
- `Data Entry` and `Awaiting Review` leaves the question of these years' & states' statuses. Are there in-progress branches of these that could be uploaded? Who is reviewing the datasets in their current form?

Again – thanks for all this hard work 😄

**Comment by pratheekrebala** [comment]
Hey @Dtphelan1,

"Excluded" generally indicates that we did not collect polling places in those states. Specifically, these states have all-mail elections so they don't have polling places in the traditional sense. For some states, e.g. Colorado - we do have drop-box locations but that's not always complete so we decided to exclude them from this data-set.

"Data Entry" means that we had to go county by county in these states to fetch polling locations, and we haven't yet had a chance to manually extract and standardize the locations in these states. In some cases (e.g. Florida) we found that the data we received from the state was incomplete and we have to most likely go back to each county.

Some of these county-by-county cases e.g. Texas, Arizona and California,  we have finished a first pass at cleaning but they haven't been reviewed for accuracy. You can find these in the "Pull Request" section of this repo. These are marked as "Awaiting Review".

You are 100% correct that there isn't sufficient documentation around this at the moment. I will work on fixing this. 

We really appreciate feedback from users like yourself and would love to learn more about your use-case and what we can do to help with your research. Please feel free to reach out to me at: prebala@publicintegrity.org.
