### ISSUE TITLE
STATUS.md Inaccuracies

### ISSUE THREAD

**Issue by Dtphelan1** [PublicI/us-polling-places#67]
This is a (non-exhaustive) list of inaccuracies in the `STATUS.md` file: 
- Tennessee:2018 says that data has been released, but there is no `data/Tennessee` folder.
- Missouri:2014, Missouri:2016, Missouri:2018 says that data has been released, but there is no `data/Missouri` folder.

**Comment by pratheekrebala** [comment]
Hey @Dtphelan1 -

Thank you for flagging this! It looks like this was an oversight on my part - I'm going check the data we have for accuracy and get back to you once it's uploaded.

Best,
Pratheek

**Comment by Dtphelan1** [comment]
That sounds great – looking forward to updates to this exciting initiative you've all been leading!

**Comment by pratheekrebala** [comment]
Hey Dylan, We've replaced the STATUS.md file with machine-readable metadata for each state and auto-generated state level STATUS files which will ensure that these types of issues shouldn't occur in the future. We've also updated the repo with data from the 2020 election.
